name: gather_link_accounts
description: Frontend app for linking Gather and other accounts.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0-417.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cloud_firestore: ^4.6.0
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  url_launcher: ^6.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
